-- Enable the pgvector extension to work with embeddings
CREATE EXTENSION IF NOT EXISTS vector;

-- Users table (required for foreign keys)
CREATE TABLE IF NOT EXISTS users (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    username VARCHAR(255) UNIQUE,
    email VARCHAR(255) UNIQUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Vehicles table
CREATE TABLE IF NOT EXISTS vehicles (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id BIGINT REFERENCES users(id),
    license_plate VARCHAR(255),
    make VARCHAR(255),
    model VARCHAR(255),
    status VARCHAR(255) CHECK (status IN ('ACTIVE', 'IN_MAINTENANCE', 'RETIRED')),
    vin VARCHAR(255),
    chassis_no VARCHAR(255),
    battery_capacity_kwh DOUBLE PRECISION,
    year_of_manufacture INTEGER,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Service History table
CREATE TABLE IF NOT EXISTS service_history (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    vehicle_id BIGINT NOT NULL REFERENCES vehicles(id),
    service_date DATE,
    total_cost NUMERIC(38, 2),
    odometer_reading BIGINT,
    description TEXT,
    provider_name VARCHAR(255),
    service_type VARCHAR(255) CHECK (service_type IN ('PREVENTATIVE', 'REPAIR', 'EMERGENCY')),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);



-- Queries table to store user questions
CREATE TABLE IF NOT EXISTS queries (
    id SERIAL PRIMARY KEY,
    user_id BIGINT REFERENCES users(id),
    vehicle_id TEXT, -- Changed to TEXT to support string IDs like 'EV-7788'
    vehicle_model TEXT,
    question TEXT NOT NULL, 
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Responses table to store answers to user queries
CREATE TABLE IF NOT EXISTS responses (
    id SERIAL PRIMARY KEY,
    query_id INT REFERENCES queries(id),
    user_id BIGINT REFERENCES users(id),
    vehicle_id TEXT, -- For mapping responses back to vehicles
    issue_id TEXT,
    answer TEXT NOT NULL,
    confidence DOUBLE PRECISION,
    status VARCHAR(50),
    title TEXT, -- For complaint context
    description TEXT, -- For complaint context
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
